security:
  access_denied_url:    ~ # Example: /foo/error403

  encoders:
       Surgeworks\CoreBundle\Entity\User:
           algorithm:        sha1
           encode_as_base64: false
           iterations:       1

  providers:
        main:
          entity: { class: Surgeworks\CoreBundle\Entity\User, property: username}

  firewalls:
      dev:
          pattern: ^/(_(profiler|wdt)|css|images|js)/
          security: false
          anonymous: ~
      #login:
          #pattern:  ^/login$
          #security: false
      secured_area:
          pattern:    ^/oauth/
          form_login:
              require_previous_session: false
              check_path: login_check
              #use_forward: false
              #always_use_default_target_path: false
              #use_referer:  false
              #failure_forward: false
              success_handler: surgeworks.security.authentication_handler
              failure_handler: surgeworks.security.authentication_handler
          logout:
              path:   logout
              success_handler: surgeworks.logout_success_handler
              #invalidate_session: false
          http_basic:
              realm: "Secured Logged Area"
      admin_area:
           pattern:    ^/oauth/admin/
           http_basic:
                realm: "Secured Admin Area"
      user_area:
           pattern:    ^/oauth/user/
           http_basic:
                realm: "Secured User Area"

  access_control:
        #- { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/admin/,  roles: ROLE_ADMIN }
        - { path: ^/oauth/user/,   roles: ROLE_USER  }

  role_hierarchy:
      ROLE_ADMIN:       ROLE_ADMIN
      ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]