parameters:
    logout_success_handler.class: 'Surgeworks\CoreBundle\Component\Authentication\Handler\LogoutSuccessHandler'
    authentication_handler.class: 'Surgeworks\CoreBundle\Component\Authentication\Handler\AuthenticationHandler'
    security_listener.class: 'Surgeworks\CoreBundle\Listeners\SecurityListener'
    user_manager.class: 'Surgeworks\CoreBundle\Services\UserManager'
    news_manager.class: 'Surgeworks\CoreBundle\Services\NewsManager'
    news_manager.rss: 'http://news.google.com/?output=rss'
    email_manager.class: 'Surgeworks\CoreBundle\Services\EmailManager'
    email_manager.params:
          username: 'username'
          password: 'password'
services:
    surgeworks.security_listener:
        class: "%security_listener.class%"
        arguments: ['@router']
        #arguments: ['@session', '@service_container', '@router', '@security.context', '@doctrine']
        tags:
            - { name: 'kernel.event_listener', event: 'security.interactive_login', method: onSecurityInteractiveLogin }
            - { name: 'kernel.event_listener', event: 'kernel.response', method: onKernelResponse }
           #- { name: 'kernel.event_listener', event: 'kernel.response', method: onKernelResponse }
    surgeworks.security.authentication_handler:
       class: %authentication_handler.class%
       public: false
       arguments: ['@router', '@session', '@security.context']
       #arguments:  ['@router', '@security.user.entity_manager']
       #tags:
          #- { name: 'monolog.logger', channel: 'security' }
    surgeworks.logout_success_handler:
        class:  %logout_success_handler.class%
        #arguments:  ['@router', '@service_container']
        tags:
            - { name: 'monolog.logger', channel: 'security' }
    surgeworks.news_manager:
        class:  %news_manager.class%
        arguments:  [%news_manager.rss%]
    surgeworks.email_manager:
        class:  %email_manager.class%
        arguments:  ['@service_container', %email_manager.params%]
    surgeworks.user_manager:
        class:  %user_manager.class%
        arguments:  ['@doctrine.orm.entity_manager']